version: '{build}'
clone_depth: 1

image:
  - Ubuntu

branches:
  only:
    - main
    - dev

configuration:
  - Release

init:
  - ps: git config --global core.autocrlf true

build_script:
  - ps: dotnet publish -c $Env:CONFIGURATION -o publish /p:Build=$Env:APPVEYOR_BUILD_NUMBER /p:IsFinalBuild=$Env:APPVEYOR_REPO_TAG src/Nexus.Writers.Mat73/Nexus.Writers.Mat73.csproj

test_script:
  - ps: dotnet test -c $Env:CONFIGURATION /p:BuildProjectReferences=false

after_build:
  - ps: cd publish; tar -zcvf ../assets.tar.gz *; cd -

artifacts:
  - path: assets.tar.gz

deploy:

# GitHub (main)
  - provider: GitHub
    force_update: true
    auth_token:
      secure: NLTKPQeVaD26Q599Si3afjQakkSEsNWPbGkcTaww3AyqYu7xRPlByGeKAtu6ruBt
    artifact: /.*\.tar.gz/
    on:
      branch: main
      APPVEYOR_REPO_TAG: true
