name: Build and Publish

on:
  push:
    branches:
      - main
      - dev

    tags:
      - '*'

jobs:

  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch tags
        run: git fetch --tags --force

      - name: Metadata
        run: echo "IS_RELEASE=${{ startsWith(github.ref, 'refs/tags/') }}" >> $GITHUB_ENV
          
      - name: Environment
        run: |
          echo "VERSION=$(python build/print_version.py ${{ github.run_number }} ${{ env.IS_RELEASE }} false)" >> $GITHUB_ENV
          echo "$(python build/print_solution.py)" >> $GITHUB_ENV

      - name: Extract annotation tag
        if: ${{ env.IS_RELEASE == 'true' }}
        run: python build/create_tag_body.py

      - name: Build
        run: dotnet publish -c Release -o publish src/Nexus.Writers.Mat73/Nexus.Writers.Mat73.csproj

      - name: Test
        run: dotnet test -c Release /p:BuildProjectReferences=false

      - name: Zip
        run: cd publish; tar -zcvf ../assets.tar.gz *; cd -

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: assets.tar.gz

    outputs:
      is_release: ${{ env.IS_RELEASE }}
      version: ${{ env.VERSION }}

  publish_dev:

    needs: build
    name: Publish (dev)
    runs-on: ubuntu-latest

    if: ${{ needs.build.outputs.is_release != 'true' }}

    steps:

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: assets.tar.gz

  publish_release:

    needs: build
    name: Publish (release)
    runs-on: ubuntu-latest

    if: ${{ needs.build.outputs.is_release == 'true' }}

    steps:

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: assets.tar.gz

      - name: GitHub Release Artifacts
        uses: softprops/action-gh-release@v1
        with:
          body_path: artifacts/tag_body.txt
          files: assets.tar.gz
